print (" -----------------------------------------------------") 
print ("|                                                     |")                                      
print ("|    01HelloWorld                                     |")
print ("|    Name : Mr Horan                                  |")                                
print ("|    Version : 01                                     |")
print ("|                                                     |")
print (" -----------------------------------------------------") 
print ("HelloWorld")
