print (" ------------------------------------------------") 
print ("|                                                |")                                      
print ("|    02GoodbyeWorld                              |")
print ("|    Name : Mr Horan                             |")                                
print ("|    Version : 01                                |")
print ("|                                                |")
print (" ------------------------------------------------") 
print ("Hello World")
input ("------> Program paused - press enter to continue")
print ("Goodbye World")